spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easypay?useSSL=false&useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnect=true&amp;useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    password:


  session:
    store-type: none


security:
  basic:
    enabled: true


server:
  port: 6080
  session:
    timeout: 100
  error:
    whitelabel: false

kkk:
  security:
    browser-properties:
      login-type: REDIRECT
#      loginPage: /demo-signIn.html